spring:
  config:
    activate:
      on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test;NON_KEYWORDS=USER;
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      authorizationserver:
        endpoint:
          token-introspection-uri:
