spring:
  spring:
    config:
      activate:
        on-profile: mysql-window
  datasource:
    url: jdbc:mysql://localhost:3306/security_jwt
    username: security_jwt
    password: security_jwt
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      authorizationserver:
        endpoint:
          token-introspection-uri:
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 300